language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

install:
  - composer self-update

  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git
  - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE phalcon_demo CHARSET=utf8 COLLATE=utf8_unicode_ci;'
  - cat schemas/phalcon_demo.sql | mysql phalcon_demo


after_script:
  - mysql -e 'DROP DATABASE phalcon_demo;'

script:
  - vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 app/controllers/ app/forms/ app/library/ app/models/ app/plugins/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    - serghei@phalconphp.com
